version: "3.7"

services:
  nginx:
    container_name: "a-nginx"
    build: ./nginx
    ports:
      - "28080:80"
    volumes:
      - ./code:/opt/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "a-php"
    volumes:
      - ./code:/opt/code

  mysql:
    image: mysql:8.0
    container_name: "a-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "23306:3306"

  redis:
    image: redis:5.0-rc
    container_name: "a-redis"
    restart: always
    ports:
      - "26379:6379"
