version: "3.7"

services:
  nginx:
    container_name: "web-server"
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/opt/code

  php:
    build: ./php
    container_name: "php"
