version: "3.7"

services:
  nginx:
    container_name: "nginx"
    # build: ./web-server 独自にubuntuをベースとしてnginxをinstallしたfile作ったがいらなそう
    image: nginx:1.14
    ports:
      - "8080:80"

  php:
    build: ./php
    container_name: "php"
